now user can see the error message.
MeiH10/RPI-EventHub pull request #268
Opened 2024-10-18 21:33 UTC by Yelnarzh

if user is not logged in and tries to like the event error message popup. Could be used for other errors since we don't have proper alert for error messages

2024-10-19 03:23 UTC, MeiH10 requested changes
there seem to be some error. i should be getting the message "log in to like an event", but i dont get that message the second time I like something
![image](https://github.com/user-attachments/assets/3e625ac2-c582-44fb-86be-577b7f6b4670)

2024-11-19 22:11 UTC, Raamzeez commented on rpi-eventhub/frontend/src/components/EventCard/EventCard.jsx
> +        console.log("Updating like count to", data.likes)
Remove console.log

2024-11-19 22:12 UTC, Raamzeez commented on rpi-eventhub/frontend/src/pages/Events/AllEventPage/AllEvents.jsx
> +            // }
Remove comment

2024-11-19 22:14 UTC, Raamzeez requested changes
Remove the console log and comment

2024-11-19 22:17 UTC, Raamzeez approved these changes

2024-11-19 22:34 UTC, MeiH10 approved these changes

2024-11-19 22:34 UTC, merged