Get the events from rpi.events.edu
MeiH10/RPI-EventHub pull request #278
Opened 2024-10-20 22:17 UTC by EdwinZhanCN

- Using the link provided to query a JSON info from rpi.events.edu
- Implement get function and format function
- Implement the api `/rpi-events` to perform a test
- Implement a automatic update function and set the node-cron update interval

## Test event inserted into the DB
**Now set the event count be 1**
**A revision can be made after review**

<img width="1044" alt="Screenshot 2024-10-20 at 6 04 39 PM" src="https://github.com/user-attachments/assets/3686d9b0-b45e-4516-abc2-21968ac51bf5">

2024-10-20 22:55 UTC, MeiH10 requested changes
sorry this is something i should have told you, but since we last talked we modified the schema for event objects. check the main for the updated schema

2024-10-21 15:17 UTC, EdwinZhanCN commented
I remove the usage of eventId when creating the Event Object, and `getNextSequence('eventId')` won't be called when event inserts

2024-10-21 15:57 UTC, EdwinZhanCN commented
The changes in the index.js about delete event by user and database connection is not my work, I believe it is the last change made in main branch.

2024-10-22 21:17 UTC, MeiH10 approved these changes

2024-10-22 21:17 UTC, merged